// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwM4S_YPyLEi60_xZ0La-fosVN85T5q6c',
    appId: '1:954659947232:web:076259b7b58bd5f4c60685',
    messagingSenderId: '954659947232',
    projectId: 'library-app-502af',
    authDomain: 'library-app-502af.firebaseapp.com',
    databaseURL: 'https://library-app-502af-default-rtdb.firebaseio.com',
    storageBucket: 'library-app-502af.appspot.com',
    measurementId: 'G-CH17YEYZEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7hIRJcEwhaPM7jycmzrCXl-wjWyIsFy0',
    appId: '1:954659947232:android:159b9b44324891b8c60685',
    messagingSenderId: '954659947232',
    projectId: 'library-app-502af',
    databaseURL: 'https://library-app-502af-default-rtdb.firebaseio.com',
    storageBucket: 'library-app-502af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8MccfJmsPAAdVVW3vU_8Z8sRlmWOAfvM',
    appId: '1:954659947232:ios:c636380db1454ae8c60685',
    messagingSenderId: '954659947232',
    projectId: 'library-app-502af',
    databaseURL: 'https://library-app-502af-default-rtdb.firebaseio.com',
    storageBucket: 'library-app-502af.appspot.com',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8MccfJmsPAAdVVW3vU_8Z8sRlmWOAfvM',
    appId: '1:954659947232:ios:c636380db1454ae8c60685',
    messagingSenderId: '954659947232',
    projectId: 'library-app-502af',
    databaseURL: 'https://library-app-502af-default-rtdb.firebaseio.com',
    storageBucket: 'library-app-502af.appspot.com',
    iosBundleId: 'com.example.libraryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwM4S_YPyLEi60_xZ0La-fosVN85T5q6c',
    appId: '1:954659947232:web:55f8e1da42c5af3ac60685',
    messagingSenderId: '954659947232',
    projectId: 'library-app-502af',
    authDomain: 'library-app-502af.firebaseapp.com',
    databaseURL: 'https://library-app-502af-default-rtdb.firebaseio.com',
    storageBucket: 'library-app-502af.appspot.com',
    measurementId: 'G-MKFDDDGGRZ',
  );

}